version: '3'


services:
  backend:
    container_name: go-server
    build: .
    ports:
      - '9000:9000'
    environment:
      - hostName=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

    
